


/*
clips: [{ story: `HEADLINES`, restrictions: `24 hours only`, categories: ``, notes: ``, hed: `"CBS Evening News" headlines for Friday, January 21, 2022`, shorthed: `"CBS Evening News" headlines for January 21, 2022`, dek: `Here's a look at the top stories making headlines on the "CBS Evening News with Norah O'Donnell."`, airtime: '', tags: [`CBS Evening News, headlines, top stories, Norah O'Donnell,`] },
{ story: `WILLIAMS+UKRAINE RUSSIA MEETING+JR+AR`, restrictions: ``, categories: ``, notes: ``, hed: `U.S. and Russia hold talks over Ukraine crisis`, shorthed: `U.S. and Russia hold talks over Ukraine crisis`, dek: `With Russina President Vladimir Putin continuing to amass troops on the border, the U.S. and its allies are sending more weapons to Ukraine. Now, the USS Harry S. Truman aircraft carrier and its strike group have moved into the region to participate in NATO maritime exercises. Holly Williams has the latest from Ukraine.`, airtime: '', tags: [`biden, NATO, europe, WWIII, invasion, aggression, united states, russia, ukraine, attack, neighboy, vadimir putin, antony blinken, secretary of state`] },
{ story: `QUINN+WINTER STORM+PARKINSON`, restrictions: ``, categories: ``, notes: `TAKE 7PM`, hed: `Southeast braces for rare ice storm`, shorthed: `Southeast braces for rare ice storm`, dek: `While much of the country is dealing with bitterly cold temperatures, the Carolinas and Virginia remain under states of emergency as snow and a rare ice storm are expected to hit the region. CBS New York chief weathercaster Lonnie Quinn has the forecast.`, airtime: '', tags: [`arctic, winter storms, South, rain, northeast, snowfall, snow, wind, advisory, weather, road crews, traffic`] },
{ story: ``, restrictions: ``, categories: ``, notes: ``, hed: ``, shorthed: ``, dek: ``, airtime: '', tags: [] }, { story: ``, restrictions: ``, categories: ``, notes: ``, hed: ``, shorthed: ``, dek: ``, airtime: '', tags: [] }]

*/